### ISSUE TITLE
ASSERTION FAILED Error when trying to use the example app

### ISSUE THREAD

**Issue by tom-23** [LabSound/LabSound#102]
I'm trying to run Simple.h and I get this error:

Thomass-Air:bin thomasbutcher$ ./LabSoundExample 
[/Volumes/DataSSD/MultiWAV/src/mw4/MultiWAV/multiwav/lib/LabSound/src/core/SampledAudioNode.cpp @ 169] ASSERTION FAILED: isLengthGood
[/Volumes/DataSSD/MultiWAV/src/mw4/MultiWAV/multiwav/lib/LabSound/src/core/OscillatorNode.cpp @ 213] ASSERTION FAILED: quantumFrameOffset <= framesToProcess
Segmentation fault: 11

**Comment by meshula** [comment]
The first assertion is in SampledAudioNode.cpp at line 169. Here is the calculation.

```c
    bool isLengthGood = destinationLength <= 4096 && numberOfFrames <= 4096;
```
I'm wondering if you could check destinationLength and numberOfFrames and report here?
Also, which backend are you using, RtAudio?

**Comment by tom-23** [comment]
Sorry for the late response, I'm using RtAudio and I'm not sure on how to check the destinationLength and numberOfFrames?

**Comment by ddiakopoulos** [comment]
@tom-23 Hi Tom, I think @meshula just means let us know what the values of `destinationLength` and `numberOfFrames` are when you hit the assert. Compile for debug and run with the debugger attached. 

This will help us trace what might be going wrong with those values. 

Also, what platform are you on? Windows?

**Comment by meshula** [comment]
We've fixed an issue that arises when an input device is not available. @tom-23, I'm wondering if you could pull latest and retest.

**Comment by meshula** [comment]
Please retest with top of tree, I'm hopeful the latest batch of fixes addresses your issue. Please reopen if there's a problem.

**Comment by tom-23** [comment]
Really sorry for the super late response, I've just ran it with the debugger attached and here is a screenshot of the values recorded:
![Screenshot 2019-05-12 at 8 13 24 pm](https://user-images.githubusercontent.com/24756018/57586769-72e48f80-74f2-11e9-8d85-c5460f876779.png)

**Comment by meshula** [comment]
Okay, that's got a really interesting clue. bufferLength is 4294995877, which is 0xffffffff as an unsigned 32 bit number, which is -1 as signed 32 bit number. bufferLength is supposed to be unsigned, so something causes a -1 to be propagated through the API. Are you running the demo in a directory that contains the samples? For example, LabSound/assets. File not found might be the issue here. Clearly something is generating a -1, and it's being erroneously passed into LabSound, so there's a bug to be addressed in LabSound as well.

**Comment by tom-23** [comment]
This is what I have set up in my build folder:

![Screenshot 2019-05-14 at 9 36 30 am](https://user-images.githubusercontent.com/24756018/57683533-cf979580-762b-11e9-8053-9bbb56a38c85.png)

I've tried using different .wav files from different sources, some exported from Ableton and some downloaded from online and this same error still persists. I've just tried running the program in the LabSound/assets directory and still get the same error.

**Comment by meshula** [comment]
Hi @tom-23, since your last comment, a number of issues have been addressed around running on macs with no microphone. I am wondering if those fixes addressed the problem you are seeing (in other words, does the latest code work)?

**Comment by tom-23** [comment]
The issue has seemed to have been fixed since I have just tried rebuilding so see that it plays the audio file and tone correctly.

**Comment by meshula** [comment]
Awesome, thanks for the update!
